# Generated by Django 5.1.4 on 2025-02-18 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="message",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="messages",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="messages",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="myapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="myapp.user",
            ),
        ),
    ]
