# Generated by Django 5.1.4 on 2025-02-18 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_messages_message_messages_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="blockchain_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="messages",
            name="timestamp",
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
