# Generated by Django 5.1.4 on 2025-02-18 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_messages_blockchain_id_alter_messages_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="timestamp",
            field=models.DateTimeField(
                null=True, verbose_name=django.utils.timezone.now
            ),
        ),
    ]
