# Generated by Django 5.1.4 on 2025-02-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_messages_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
