# Generated by Django 5.1.4 on 2025-02-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_messages_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="f_key",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
