# Generated by Django 5.1.4 on 2025-02-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_messages_f_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="f_key",
        ),
    ]
